### ISSUE TITLE
Downloading files

### ISSUE THREAD

**Issue by DuaneW2017** [Yagisan/SS2-City-Plan-Contest-Helper#1]
Not really an issue. More of an observation.
Seven Threads were going simultaneously the whole time. 
Downloading went very slowly.
I never download more than one or two files at a time.
Goes much faster. (on my computer) IMO.

**Comment by Yagisan** [comment]
Hi,

That's a wabbajack application setting. The optimal number really depends on both your internet connection, and what lists you are downloading. For example, my TBV list has a lot of very small files, so it works rather well with the default wabbajack settings. This list, on my home internet connection, works better if I reduce the number of downloads for an initial installation. Upgrades don't really care as usually, very few files change between updates.

Unfortunately, it isn't something I can change via the SS2CPC Helper, so I'm going to close this report. Thank you for reporting your experiences.

**Comment by DuaneW2017** [comment]
Thank you for your reply.
Maybe someday a pop up could make this adjustable.
