### ISSUE TITLE
"Unable to download Data_DLC..."

### ISSUE THREAD

**Issue by GwenstheName** [Yagisan/SS2-City-Plan-Contest-Helper#2]
When performing a WJ or Manual Install, WJ goes through and downloads all the mod archives, but cannot locate specifically the DLC archives. BA2 Files are under the appropriate Fallout 4>Data location in a working file directly on my disk. Please find attached the WJ log file
[Wabbajack.UnabletoDownloadDLCData.GtN.log](https://github.com/Yagisan/SS2-City-Plan-Contest-Helper/files/12360322/Wabbajack.UnabletoDownloadDLCData.GtN.log)

**Comment by Yagisan** [comment]
Have you "Cleaned" your master files?

- dlcrobot.esm
- dlccoast.esm
- dlcnukaworld.esm
- dlcworkshop01.esm
- dlcworkshop02.esm
- dlcworkshop03.esm

These DLC are not matching the checksum for an untouched install. In Steam, Right click on Fallout 4, select properties, select installed files, then select verify integrity of game files. When it is complete, if you re-run the wabbajack, it will complete successfully.

**Comment by GwenstheName** [comment]
Issue is resolved, thank you!
