### ISSUE TITLE
Loading old mod

### ISSUE THREAD

**Issue by Skywise001** [Yagisan/SS2-City-Plan-Contest-Helper#3]
One of the mods (I think its Nora's) is trying to access and download a file thats been retired on Nexus.  Just wanted to let you know.

I hope this is the right place for this comment.  Thank you so much for your work.

**Comment by Yagisan** [comment]
Thank you for letting me know. I don't generally release an update mid-contest unless there are essential bug fixes. All addon packs will be updated to the latest release for the 4.3.0 - Season 4 - February 2024 release, and are already updated locally. This will be out after the February contest is announced and the City Plan Contest mod is updated.
