### ISSUE TITLE
SS2-City-Plan-Contest-Helper NG

### ISSUE THREAD

**Issue by shirha** [Yagisan/SS2-City-Plan-Contest-Helper#4]
Does the list work with Fallout 4 Next-Gen 1.10.984 or should I downgrade to 1.10.163 first?

**Comment by Yagisan** [comment]
This list requires you to have the Fallout 4 Next-Gen 1.10.984 installed via Steam. **It will then duplicate it, and automatically downgrade it to Fallout 4 1.10.163**, including rebuilding the BA2 files (This is why the first installation is slow - but upgrades are fast).

It also includes support for running Next-Gen format BA2 files, should you wish to modify the list (although I can't provide support for modified lists)
